// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-kOjgwYIEQMsEWhPxxknWzzlfquFihpA',
    appId: '1:372890320799:web:6714147f6823741a2647aa',
    messagingSenderId: '372890320799',
    projectId: 'fypiot-2804d',
    authDomain: 'fypiot-2804d.firebaseapp.com',
    storageBucket: 'fypiot-2804d.firebasestorage.app',
    measurementId: 'G-W1ZHFMGYNV',
    databaseURL: 'https://fypiot-2804d-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4H3By1lTZAvQN85uSrRYuvTKEo2royNI',
    appId: '1:372890320799:android:2764f822d08b5a9b2647aa',
    messagingSenderId: '372890320799',
    projectId: 'fypiot-2804d',
    storageBucket: 'fypiot-2804d.firebasestorage.app',
    databaseURL: 'https://fypiot-2804d-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJLy62gS2brYiukJGjKNTCXS8cbicQtuo',
    appId: '1:372890320799:ios:5070e0c0c1fd62e82647aa',
    messagingSenderId: '372890320799',
    projectId: 'fypiot-2804d',
    storageBucket: 'fypiot-2804d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
    databaseURL: 'https://fypiot-2804d-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJLy62gS2brYiukJGjKNTCXS8cbicQtuo',
    appId: '1:372890320799:ios:5070e0c0c1fd62e82647aa',
    messagingSenderId: '372890320799',
    projectId: 'fypiot-2804d',
    storageBucket: 'fypiot-2804d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
    databaseURL: 'https://fypiot-2804d-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-kOjgwYIEQMsEWhPxxknWzzlfquFihpA',
    appId: '1:372890320799:web:ff9e154cc8ea138f2647aa',
    messagingSenderId: '372890320799',
    projectId: 'fypiot-2804d',
    authDomain: 'fypiot-2804d.firebaseapp.com',
    storageBucket: 'fypiot-2804d.firebasestorage.app',
    measurementId: 'G-VKE65VHP9Y',
    databaseURL: 'https://fypiot-2804d-default-rtdb.firebaseio.com/',
  );
}
